version: '3.8'
services: 
  db: 
    image: postgres:15-alpine #Imagem do PostgreSQL
    container_name: postgres_industrial # Nome que vai aparecer no Docker
    restart: always
    environment: #Aqui será definido as credencuaus idênticas ao application.properties
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: industrial_db
    ports: #Mapeia a porta 5432 do computador (esquerda) para a porta 5432 do container (direita)
      - "5432:5432"
    volumes: # Salva os dados no disco rígido para não perder o container
      - postgres_data:/var/lib/postgresql/postgres_data
  backend:
    build: ./demo # Diz ao Docker para procurar o Dockerfile dentro da pasta demo
    container_name: backend_industrial
    restart: always
    ports:
      - "8080:8080" # Permite-nos aceder à API pelo nosso navegador depois
    depends_on:
    - db # Regra vital: O Java só pode iniciar DEPOIS que o banco de dados estiver pronto
  sensor-prensa:
    build: . # O ponto (.) diz ao Docker para procurar o Dockerfile nesta mesma pasta (raiz)
    container_name: sensor_prensa_01
    depends_on:
      - backend # Regra vital: O Python só começa a enviar dados DEPOIS que a API Java estiver no ar
    # Passamos o nome da máquina para o nosso script sensor.py
    command: ["python", "-u", "sensor.py", "PRENSA-HIDRAULICA-01"]
    
volumes:
  postgres_data: