spring.application.name=demo
# A porta onde o Java vai rodar
server.port=8080

# O endereço do nosso Banco de Dados no Docker
spring.datasource.url=jdbc:postgresql://db:5432/industrial_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Magia do Spring: Cria a tabela automaticamente se ela não existir
spring.jpa.hibernate.ddl-auto=update
# Mostra no console os comandos SQL que o Java está a executar (bom para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true